export const profile = {
  name: 'Vishal Vaibhav',
  role: 'principal engineer · systems & search',
  location: 'bengaluru',
  email: 'hello@example.com',
  linkedin: 'https://www.linkedin.com/in/vishal-vaibhav-29b25328/',
  lastEdit: '2026-04-22',
}

export const posts = [
  {
    slug: 'designing-for-search-at-scale',
    date: '2026-04-22',
    tag: 'systems',
    title: 'Designing for search at scale: notes from the trenches',
    read: '12 min',
    deck: 'What I keep relearning about index layout, query planning, and the cost of being clever.',
  },
  {
    slug: 'the-quiet-art-of-capacity-planning',
    date: '2026-03-14',
    tag: 'ops',
    title: 'The quiet art of capacity planning',
    read: '8 min',
    deck: 'Numbers on a napkin still beat dashboards most days.',
  },
  {
    slug: 'writing-systems-for-the-next-engineer',
    date: '2026-02-02',
    tag: 'craft',
    title: 'Writing systems for the next engineer',
    read: '6 min',
    deck: 'The code you leave behind is a letter. Make it readable.',
  },
  {
    slug: 'vector-search-without-the-magic',
    date: '2025-12-09',
    tag: 'search',
    title: 'Vector search without the magic',
    read: '14 min',
    deck: 'An honest walk through ANN, recall trade-offs, and where intuition fails.',
  },
  {
    slug: 'on-being-a-principal-engineer',
    date: '2025-10-28',
    tag: 'career',
    title: 'On being a principal engineer (and not a bottleneck)',
    read: '9 min',
    deck: 'Influence is a budget. Spend it on the things only you can do.',
  },
  {
    slug: 'five-databases-in-five-years',
    date: '2025-09-03',
    tag: 'systems',
    title: "Five databases in five years, and what I'd choose tomorrow",
    read: '11 min',
    deck: 'A field report from someone who has migrated more than he should have.',
  },
  {
    slug: 'the-cost-of-a-good-abstraction',
    date: '2025-07-19',
    tag: 'craft',
    title: 'The cost of a good abstraction',
    read: '7 min',
    deck: 'Abstractions are loans. Pay attention to the interest rate.',
  },
  {
    slug: 'always-be-building',
    date: '2025-05-30',
    tag: 'notes',
    title: 'Always be building',
    read: '4 min',
    deck: 'Why I keep a notebook of unfinished systems, and what they taught me.',
  },
]
